import { format } from 'date-fns';
import { CheckResult } from '../checks';
import { writeText } from '../utils/fs';
import path from 'path';

export async function generateChecklist(
  targetDir: string,
  results: CheckResult[]
): Promise<string> {
  const passed = results.filter((r) => r.passed).length;
  const total = results.length;
  const date = format(new Date(), 'yyyy-MM-dd HH:mm:ss');
  const status = passed === total ? '🟢 Ready to ship' : passed >= total / 2 ? '🟡 Almost ready' : '🔴 Not ready';

  const lines: string[] = [
    '# ⛵ Release Checklist',
    '',
    `> Generated by ShipCheck on ${date}`,
    `> Scanned: \`${targetDir}\``,
    '',
    `**Status:** ${status}  `,
    `**Score:** ${passed} / ${total} checks passed`,
    '',
    '---',
    '',
    '## Checks',
    '',
  ];

  for (const r of results) {
    const icon = r.passed ? '- [x]' : '- [ ]';
    lines.push(`${icon} **${r.name}** — ${r.detail}`);
  }

  const failed = results.filter((r) => !r.passed);
  if (failed.length > 0) {
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## What to fix');
    lines.push('');
    for (const r of failed) {
      lines.push(`### ${r.name}`);
      lines.push('');
      lines.push(r.fix ?? 'No fix suggestion available.');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by [ShipCheck](https://github.com/lowkeyjojo/shipcheck)_');
  lines.push('');

  const content = lines.join('\n');
  const outPath = path.join(targetDir, 'RELEASE_CHECKLIST.md');
  await writeText(outPath, content);
  return outPath;
}
