import { format } from 'date-fns';
import { CheckResult } from '../checks';
import { PresetSuggestion } from '../presets';
import { writeText } from '../utils/fs';
import path from 'path';

export async function generateCodex(
  targetDir: string,
  results: CheckResult[],
  preset: string,
  suggestions: PresetSuggestion[]
): Promise<string> {
  const failed = results.filter((r) => !r.passed);
  const date = format(new Date(), 'yyyy-MM-dd HH:mm:ss');

  const lines: string[] = [
    '# ⛵ Release Readiness Tasks',
    '',
    '> Auto-generated by ShipCheck for Codex / AI agent consumption.',
    `> Generated: ${date}`,
    `> Project: \`${targetDir}\``,
    `> Preset: \`${preset}\``,
    '',
    '---',
    '',
  ];

  if (failed.length === 0) {
    lines.push('## ✅ No required tasks — all checks passed');
    lines.push('');
    lines.push('This project passed all ShipCheck release-readiness checks.');
    lines.push('');
  } else {
    lines.push(`## Required Tasks (${failed.length})`);
    lines.push('');
    lines.push('The following issues must be resolved before this project is ready to ship.');
    lines.push('');

    failed.forEach((r, i) => {
      lines.push(`### Task ${i + 1}: Fix missing ${r.name}`);
      lines.push('');
      lines.push(`**Check:** ${r.name}`);
      lines.push(`**Issue:** ${r.detail}`);
      lines.push(`**Action required:** ${r.fix ?? 'Resolve the issue described above.'}`);
      lines.push('');
      lines.push('```');
      lines.push(`# Suggested action for: ${r.name}`);
      lines.push(`# ${r.fix ?? 'See issue description above.'}`);
      lines.push('```');
      lines.push('');
      lines.push('---');
      lines.push('');
    });
  }

  if (suggestions.length > 0) {
    const presetLabel = preset.charAt(0).toUpperCase() + preset.slice(1);
    lines.push(`## Optional ${presetLabel} Preset Reminders`);
    lines.push('');
    lines.push('These are advisory items specific to the selected preset. Review before shipping.');
    lines.push('');

    suggestions.forEach((s, i) => {
      lines.push(`### Reminder ${i + 1}: ${s.label}`);
      lines.push('');
      lines.push(s.detail);
      lines.push('');
    });

    lines.push('---');
    lines.push('');
  }

  lines.push('_Generated by [ShipCheck](https://github.com/lowkeyjojo/shipcheck)_');
  lines.push('');

  const content = lines.join('\n');
  const outPath = path.join(targetDir, '.codex', 'tasks', 'release-readiness.md');
  await writeText(outPath, content);
  return outPath;
}
