import { format } from 'date-fns';
import { CheckResult } from '../checks';
import { writeText } from '../utils/fs';
import path from 'path';

export async function generateCodex(
  targetDir: string,
  results: CheckResult[]
): Promise<string> {
  const failed = results.filter((r) => !r.passed);
  const date = format(new Date(), 'yyyy-MM-dd HH:mm:ss');

  const lines: string[] = [
    '# ⛵ Release Readiness Tasks',
    '',
    '> Auto-generated by ShipCheck for Codex / AI agent consumption.',
    `> Generated: ${date}`,
    `> Project: \`${targetDir}\``,
    '',
    '---',
    '',
  ];

  if (failed.length === 0) {
    lines.push('## ✅ No tasks — all checks passed');
    lines.push('');
    lines.push('This project passed all ShipCheck release-readiness checks.');
    lines.push('No action is required.');
    lines.push('');
  } else {
    lines.push(`## Open Tasks (${failed.length})`);
    lines.push('');
    lines.push('The following tasks must be completed before this project is ready to ship.');
    lines.push('');

    failed.forEach((r, i) => {
      lines.push(`### Task ${i + 1}: Fix missing ${r.name}`);
      lines.push('');
      lines.push(`**Check:** ${r.name}`);
      lines.push(`**Issue:** ${r.detail}`);
      lines.push(`**Action required:** ${r.fix ?? 'Resolve the issue described above.'}`);
      lines.push('');
      lines.push('```');
      lines.push(`# Suggested action for: ${r.name}`);
      lines.push(`# ${r.fix ?? 'See issue description above.'}`);
      lines.push('```');
      lines.push('');
      lines.push('---');
      lines.push('');
    });
  }

  lines.push('_Generated by [ShipCheck](https://github.com/lowkeyjojo/shipcheck)_');
  lines.push('');

  const content = lines.join('\n');
  const outPath = path.join(targetDir, '.codex', 'tasks', 'release-readiness.md');
  await writeText(outPath, content);
  return outPath;
}
