import { format } from 'date-fns';
import { CheckResult } from '../checks';
import { PresetSuggestion } from '../presets';
import { writeText } from '../utils/fs';
import path from 'path';

export async function generateReport(
  targetDir: string,
  results: CheckResult[],
  preset: string,
  suggestions: PresetSuggestion[]
): Promise<string> {
  const passed = results.filter((r) => r.passed).length;
  const total = results.length;
  const date = format(new Date(), 'yyyy-MM-dd HH:mm:ss');
  const score = Math.round((passed / total) * 100);

  const lines: string[] = [
    '# ⛵ ShipCheck Report',
    '',
    `| Field | Value |`,
    `|---|---|`,
    `| Generated | ${date} |`,
    `| Scanned path | \`${targetDir}\` |`,
    `| Preset | \`${preset}\` |`,
    `| Score | ${passed} / ${total} (${score}%) |`,
    `| Status | ${passed === total ? '✅ Ready to ship' : passed >= total / 2 ? '⚠️ Needs attention' : '❌ Not ready'} |`,
    '',
    '---',
    '',
    '## Results',
    '',
    '| Status | Check | Detail |',
    '|---|---|---|',
  ];

  for (const r of results) {
    const icon = r.passed ? '✅' : '❌';
    lines.push(`| ${icon} | **${r.name}** | ${r.detail} |`);
  }

  const failed = results.filter((r) => !r.passed);
  if (failed.length > 0) {
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Recommended Fixes');
    lines.push('');
    for (const r of failed) {
      lines.push(`### ❌ ${r.name}`);
      lines.push('');
      lines.push(`**Issue:** ${r.detail}`);
      lines.push('');
      lines.push(`**Fix:** ${r.fix ?? 'No suggestion available.'}`);
      lines.push('');
    }
  } else {
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## All checks passed! 🎉');
    lines.push('');
    lines.push('Your project looks ready to ship. Double-check your changelog and version bump before releasing.');
    lines.push('');
  }

  if (suggestions.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push(`## ${preset.charAt(0).toUpperCase() + preset.slice(1)} Preset Suggestions`);
    lines.push('');
    lines.push('These are advisory reminders — review before shipping:');
    lines.push('');
    for (const s of suggestions) {
      lines.push(`### 💡 ${s.label}`);
      lines.push('');
      lines.push(s.detail);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by [ShipCheck](https://github.com/lowkeyjojo/shipcheck)_');
  lines.push('');

  const content = lines.join('\n');
  const outPath = path.join(targetDir, '.shipcheck', 'report.md');
  await writeText(outPath, content);
  return outPath;
}
